package sfwrap

import (
	"fmt"
	"os"
)

// GenerateSfEmbedGo generates a Go source file that embeds the given signature file as a byte slice.
// outPath is typically "internal/sfwrap/sfembed.go"
func GenerateSfEmbedGo(sigPath, outPath string) error {
	data, err := os.ReadFile(sigPath)
	if err != nil {
		return fmt.Errorf("could not read signature file: %w", err)
	}
	varName := "sig"
	// Write Go file
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("could not create embed file: %w", err)
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "// Code generated by sfembedgen.go; DO NOT EDIT.\npackage sfwrap\n\nvar %s = []byte{\n", varName)
	if err != nil {
		return err
	}
	// Write bytes as comma-separated hex
	for i, b := range data {
		if i%12 == 0 {
			_, err = fmt.Fprint(f, "\n\t")
			if err != nil {
				return err
			}
		}
		_, err = fmt.Fprintf(f, "0x%02x,", b)
		if err != nil {
			return err
		}
	}
	_, err = fmt.Fprintln(f, "\n}")
	return err
}

// Utility: Run this from a small Go program or from update-signatures for manual embed.
// Example usage:
//   err := sfwrap.GenerateSfEmbedGo("internal/sfwrap/signatures/default.sig", "internal/sfwrap/sfembed.go")
